### ISSUE TITLE
SR-17-0000475 FD Increase Fees 

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#19]
FD Increase Fees - 

Fire will be increasing their fee's in 2018 by about 25%. This still needs to go through Common Council and would then need to be activated in production the next day. We will pre-emptively get these in as a new fee schedule and then set the effective date once we know when it's going to be in place. 

This should include all Fire Fees except Elevators.

- [x] First we need to provide Fire with all their current Fee Schedules
- [x] Need to update them and test that they are working and have increased 
- [x] After UAT, we can push these to production but not enabled
- [x] Once we have an idea for the go date, we can set the effective date accordingly and set the old ones to expire after 30 days
-  - [x] The effective date of the new Fee Schedules will be May 1st

## Scope Change!
Fire has a number of inspection and possibly plan review letter reports that have the re-inspection or other fee amounts hard-coded. I would like to switch these to look at the latest effective fee schedule.
 - [x] Identify the Reports that need to change => No reports need to change. Just the Standard Comment for Plan Review, see below for specifics
 - [x] Update them to use the fee lookup function
 - [x] Increase the License Fees to be $125 from $100
 - [x] Add to the reinspection fee invoice => Riki 4/16/2018 - Not needed
![image](https://user-images.githubusercontent.com/13784495/38690419-aece0800-3e43-11e8-9c92-71a97d402ee5.png)
Riki 4/16/2018 -
 - [ ] The installing contractor shall conduct a complete system pretest prior to scheduling an acceptance test with MFD. A re-inspection fee will be assessed if the system or system components fail to comply with the applicable codes.
![image](https://user-images.githubusercontent.com/13784495/38828229-080ab2da-417b-11e8-98f8-93487d3b39c1.png)

## Questions for Fire
- [x] FIRALYS - FACU going up by 150 from 100 to 250 & FAID going down by 75  from 200 to 125 => Riki 4/16/2018 - This is correct. Spoke with Bill and some fees are going down.
- [x] FIRCONEGR - ALTCES going down by 75 from 200 to 125 => Riki 4/16/2018 - This is correct. Spoke with Bill and some fees are going down.

**Comment by RikiSjachrani-COM** [comment]
![image](https://user-images.githubusercontent.com/13784495/34173017-98fdc576-e4b9-11e7-8719-1b1cd146039a.png)

**Comment by ChrisHagen-COM** [comment]
Attached is the updated Fire schedules


[Fee Schedules.xlsx](https://github.com/City-of-Madison/Development-Team-2/files/1579734/Fee.Schedules.xlsx)

**Comment by RikiSjachrani-COM** [comment]
Sent an email to Bill and cc'ed @ChrisHagen-COM

**Comment by ChrisHagen-COM** [comment]
Has there been any movement on this?

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM I've attached the most recent "In-Progress" fee updates, I'll ask whether they've made any additional movement on it, otherwise, please take a look and start to think about how to implement and track these fee changes.
[Accela MGO 2018 Fee.Schedules.xlsx](https://github.com/City-of-Madison/Development-Team-2/files/1885567/Accela.MGO.2018.Fee.Schedules.xlsx)

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM this is set to go live by May 1st, could we get together and figure out the amount of remaining effort to get it into Dev...Test by next week?

**Comment by RikiSjachrani-COM** [comment]
@JacquelineGoltz-COM I'm going to put a meeting together, we need to get this moving

**Comment by JacquelineGoltz-COM** [comment]
Looks like someone already updated them in DEV.

**Comment by RikiSjachrani-COM** [comment]
oh? I wonder how that happened? I wonder how far those changes went => Test? => Production?

**Comment by JacquelineGoltz-COM** [comment]
The FIRLICENSE and FIRHAZMAT etc. are on Chris's part of the list.  IS there a different license fee that I am missing?

**Comment by ChrisHagen-COM** [comment]
Yup, I'm just working my way down the list so that's why they were updated already.

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM when you provided the list of fee schedules for fire, you provided all of them including the License ones? If so, they should be accounted for in the updated spreadsheet

**Comment by ChrisHagen-COM** [comment]
Yes, the first 5 on the list were licenses.

I think we removed the elevator licenses.

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM Those are all done updated at this point..

**Comment by RikiSjachrani-COM** [comment]
I don't think there are any elevator licenses, we removed the elevator permits...just to clarify

**Comment by RikiSjachrani-COM** [comment]
Let me take a look, what you are suggesting is plausible, I think all the fees are going up and none are dropping

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM about the FIRALSYS fee that switched, just go with the increased amount and don't drop it down at all. 

@JacquelineGoltz-COM and @ChrisHagen-COM please add to the top of here any questions you may have, I'm going to give the fire guys a call tomorrow

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 
Everything is done in my section except the following few notes and few questions:

FIRECONEGR - spreadsheet shows ALTCES (Repair to Existing Cotrolled Egress) is dropping from 200 to 125. **Is this correct?**

FIRECONEGR - NACES - The new fee calls for "250 per 10 doors or fraction there of". The corresponding field showing the number of doors is a text field. **What is the best way to handle this?** If we change the field to numerical I think we'd lose any non numerical data. I could possibly put in an expression that blocks input if a non numerical number is placed in the field. From there we can round up to nearest 10 by dividing by 10, & rounding up and using that number to multiply by the fee. 

FIRWRKDISP, FIRNATLWN and FIRGENBRN did not change. I did not notice that FIREGENBRN did not change until after I already created a new version. I did not touch the other two. Unsure if there is a way to remove the 4.0 fee from FIGENBRN or if we need to. 


Thanks!

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 
RE:  FIRECONEGR - NACES -- '250 per 10 doors or fraction thereof' change

I did a search of all "List Controlled Doors" text field out there. Most of them have the number of doors, but there are some that have a unit number or some other text. So we can't convert what's there.

Maybe we need to create a new field like "Total Number of Controlled Doors added or altered" (Right now altered is a constant fee kicked off by a "Alter Controlled Egress" checkbox, but this way the field could be used in the future if it changes to a similar fee)

Thanks!

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

I don't think I can use any set fees because there is no way to force any sort of rounding. I think we need to use a script for that. 

The calculation in script would be pretty easy:

fee = (Math.ciel({Scope of Work:List Controlled Doors} * 0.1) * 250)

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

I realized I didn't post it here, I wanted to make sure you did know that I ensured the constant fee changes for FIRALSYS and FIRCONEGR are set per our meeting. Only thing outstanding is the FIRECONEGR/NACES which you told to hold on if I couldn't find a working built in formula.

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM can't we use something like FIXED_FEE_BY_RANGE_MULTIPLIER?

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM Re-reading it again, I guess I could try to set up one range going by the last line in the manual on this: 

• If you set up only one range, the fee is always equal to the fee for that range multiplied by the user
input.

I'll see what happens.

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM Also, do you have the updated spreadsheet? Specifically the column names alias wording to the right of NACES? You showed me that this morning and said that I should alias the existing column (which I can't, per previous note above). I see the copy of the excel document in here is just a static copy so I can't see that change. 
I took notes on the other stuff, formula, etc, and noted to use spreadsheet name as alias... 
Thanks.

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

I went ahead and set up a temp test field to at least test the fee changes while we decide on a permanent name. 

I used FIXED_FEE_BY_RANGE_MULTIPLIER and used $FI10392$,250,10 as my range and added a fee and it did nothing with a value of 2 in the field. 

I upped it to $FI10392$,250,10, 500, 20 and added a value and it calculated correctly. I changed that to 14 and it came back as 0. 

I can put into 500 characters into this, so I can conceivably take this out to 2-300 doors but as soon as it gets to X+1 door it becomes a problem. I can't think of any building needing this many doors facing outside or to exit stairs, but I don't know exactly how they use this. 

Is there some way to put in a notification for someone if they put in a larger number they will have to add another fee manually? Is that an acceptable limitation?

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM I think you are correct that we will have to make an exception for this. We can talk further about using a formula or just stringing out the calculation with the FIXED_FEE_BY_RANGE Formula. The main thing would be so that they enter a value in the "Number of Doors" and they use 1 for the quantity of the fee item, then it calculates correctly. If we end up using a formula, we should still use a fee item type that works with it

**Comment by RikiSjachrani-COM** [comment]
I've attached my notes after meeting with Fire
[Accela.MGO.2018.Fee.Schedules v2.xlsx](https://github.com/City-of-Madison/Development-Team-2/files/1915731/Accela.MGO.2018.Fee.Schedules.v2.xlsx)

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

I created a new field for FIRACCEGR called "Number of Doors". I was not able to change the text field into a number as noted before.

I setup the fee to go out to 300 ($7500). Everytime it is updated it triggers either 
      CMN:Permitting/Fire/ControlledEgress/NA:Fee
or
      CMN:Permitting/Fire/ControlledEgress/NA:FeeACA


The ACA just sends an email to the customer and fire explaining that it applies, it adds no fees at this time. 

I changed the old field to say "Controlled Doors (Historical)" that is NOT visible from ACA and it's at the bottom. I am not sure how to best handle that field, and I am not sure how/or if we should notify fire to change the quantity if they need more than 300 doors. (I am having a hard time thinking of a single building that would have that many to begin with, maybe one of the hospitals?)

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM great I spoke with Bill and the most he's ever seen is 100 doors for UW West. 

@JacquelineGoltz-COM please feel free to promote changes to Test if the QA is done. I'll deal with the Standard Choice change that replaces the reporting changes

**Comment by RikiSjachrani-COM** [comment]
I'm modifying the following Standard Choices to make the Re-inspection Fee comment more general. 

BIZDOMAIN	BIZDOMAIN_VALUE
FIRE ALARM PERMIT CONDITIONS	06
FIRE ALT SUPPRESSION COND	03
FIRE CONTROLLED EGRESS COND	05
FIRE SPRINKLER PERMIT COND	05

**Comment by ChrisHagen-COM** [comment]
I added the new "Number of Doors" to FIRACCEGR. I added an alias to List Controlled Doors: "Controlled Doors (Historical)" and made it not viewable on ACA. 

Will test Egress, then test all of jackie's items using a end user's credentials in Test.

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

I tested this on Test as an end user and ran into an issue with 0 doors that we did not catch in dev. I then worked with @JacquelineGoltz-COM as a sanity check in what what happening. 

This is concerning Permitting/Fire/ControlledEgress/NA.  Since the new fee for FIRCONEGR/NACES is a formula that uses a fee indicator, I have to make it required for it to work correctly. The issue is if the number of doors is 0, it errors out. I looked online at accela support and verified that most of the fee formulas do not allow you to use a 0, as that would result in a fee with 0 cost. 

Looking at CMN:Permitting/Fire/ControlledEgress/NA:Fee, I see that both "New Controlled Egress" and "Alter Control Egress" triggered the NACES fee. There is also a fee that for "Repair to Existing Controlled Egress" that is not trigged through workflow. There used to be a "Repair Existing Controlled Egress" that has since been removed from the system that triggered this, so the only way it's added is manually.

I suspect it wasn't really used though because the fee went to the same account code and was the same cost as the new/alter fee was. Now that it's only 125 versus 250 per set of 10 doors, I imagine it will potentially be used more often?

There's two things I can think of to fix this:

One would be a popup triggered using the before action stating that if the New or Alter functions are checkmarked, the number needs to be a 1 or higher. 

Alternatively we could modify the script slightly by adding the bolded portion below:
({SCOPE OF WORK.New Controlled Egress} == "CHECKED" || {SCOPE OF WORK.Alter Controlled Egress}  == "CHECKED" ) && **{SCOPE OF WORK.Number of Doors} != 0** ^ if(feeExists("NACES") == false) updateFee("NACES","FIRCONEGR","FINAL",1,"N");^ if(feeExists("NACES") == true) removeFee("NACES","FINAL");

**Comment by RikiSjachrani-COM** [comment]
I can double check with Fire, but wouldn't we expect at least 1 door for this type of permit, or why would they be applying for it.

Also,
1) Please remove the "Controlled Doors (Historic)" it's not needed anymore
2) Did anyone QA this in ACA?

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

If I disable the List Controlled Doors/Controlled Doors (Historical) won't they not be able to see what was put in there on existing, open cases that are not using the latest fee schedule? Or does it still display on items that had it (I don't think I've ever done this, so I'm not sure)

Thanks

**Comment by RikiSjachrani-COM** [comment]
It stays on historical records

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

For the ACA testing I'm doing that as part of the next testing phase, including testing things internally as a user (Anne B). I changed the EML:Permitting/Fire/*/*:FeeACA to email @JacquelineGoltz-COM  and myself. It doesn't look like it does the fees when submitting from ACA, but I'll run through them to make sure.

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM I just want to make sure the new field is in ACA for the customers.

@JacquelineGoltz-COM are all the fees in Test then? I need to update the customer that it's ready

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

@JacquelineGoltz-COM just informed me that it does do the fees on submission (it just doesn't displa any to the applicant)

When I tested the controlled egress it failed to submit and generated an error if the user puts in a 0. I will need to create a expression builder for that so that number entered is a 1 or higher. 


Additionally I discovered that Permitting/fire/AltFireSuppression/NA is not working with NAFSS ("New, Alter Alternative Fire Suppression"). When I added in the new formulas in dev I added them, then checked Jackie's work. I understand now that I need to add a field that corresponds to the value in the new formula. I am guessing the 2nd number f each tier in the formula (as shown below) is square footage?

@RikiSjachrani-COM can you confirm that?

$FI10397$,250,2500,315,5000,375,10000,750,20000,1125,30000,1500,40000,1875,50000,2250,75000,2625,100000,3000,200000,3375,300000,3750,400000,4125,500000,4500,9999999,4500

**Comment by RikiSjachrani-COM** [comment]
Please work with Jackie on the Alternative Fire Suppression concern, I didn't think we need to add a new field for this...confused?

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

For Permitting/Fire/ControlledEgress/NA    FIRCONEGR
I created a new Expression builder for ACA that places the message "The number of doors must be 1 or greater" that triggers on submission or edit of the Number of doors field and tested it successfully. This expression triggers a blockSubmit if the number is 0. 

I then went in and tested the fees using Anne B's account to make sure that all the new fees were showing up as expected. 

I need @JacquelineGoltz-COM to QA this as well on Test. 

@JacquelineGoltz-COM  - Do you have time to work together about the new field for Alternate Fire Suppression? I don't see any fields we can repurpose for this, there is no existing numerical fields on the custom fields tab for this.

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM is there not an existing field already?

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM    @JacquelineGoltz-COM  is looking over my shoulder, she confirms there's no existing fields to be repurposed. We need a numerical field on there.

We am guessing you'll need to check with fire on wording for field and to confirm the unit is Sq Foot. (and maybe confirm with them that they really did want to change this to a range formula, not just increase the constant to 250)

![image](https://user-images.githubusercontent.com/30443079/38888540-8d6cbc9a-4241-11e8-9d17-966d27feed2e.png)

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM , @JacquelineGoltz-COM 

Project Area has been added to Alternate Fire Suppression. Jackie also had me put in a tooltip for it as well as wording the message that occurs if someone sets the value at 0 to be "The square footage needs to be greater than 0". 

This has been tested in TEST and DEV. 


Based on a discussion with Jackie, Sharon and Myself I will also add a field called "Alter 3 or less Alternate Fire Suppression Devices". This will be a hidden field that is only visible when Alter has been chosen. If this field is checked, we will NOT run the tiered NAFSS fee, but instead run a new fee of 125. 

This change will involve expression builder changes for when it's displayed and when the sq footage will be required, and scripting changes to CMN:Permitting/Fire/AltFireSuppression/NA:Fee so that the NAFSS fee is not run and the new fee is added instead. I will use the existing script as a template for that and will work on that first thing tomorrow morning.

-Chris

**Comment by ChrisHagen-COM** [comment]
email of conversation between jackie and bill attached 
[FW Accela Fee 3or less .txt](https://github.com/City-of-Madison/Development-Team-2/files/1921539/FW.Accela.Fee.3or.less.txt)

**Comment by ChrisHagen-COM** [comment]
@JacquelineGoltz-COM 

I added the new fee, field, script changes and expressions needed to Alternate Fire Systems for the "Alter 3 or less Alternate Fire Suppression Devices". I'll write a followup document outlining the procedures needed to put all of those changes into place on PROD. I'll also include the changes needed for FIRCONEGR/NACES for the number of Doors.

Once you verify it is working in DEV I'll move it up to test so that we can finish testing Fire with Anne's login so @RikiSjachrani-COM can get this sent up to them for verification.

**Comment by JacquelineGoltz-COM** [comment]
@ChrisHagen-COM I ran two records in dev for Alt Fire Systems and the fees are correct.  I did add an Onload Ex Bldr to hide the new field upon onload. I will move the change to test as well. 
Bill wants to know if we can set him up to test.  Are we ready?

**Comment by ChrisHagen-COM** [comment]
Below are the instructions to move this to production.

@JacquelineGoltz-COM  --- have you been able to test the "Alternate Fire Systems" so I can move from DEV to TEST?

[Fire Updates that involve more than Fee updates.pdf](https://github.com/City-of-Madison/Development-Team-2/files/1925455/Fire.Updates.that.involve.more.than.Fee.updates.pdf)

**Comment by ChrisHagen-COM** [comment]
@JacquelineGoltz-COM Looks like we posted at the same time! :)

I have not finished going through all of them yet, I'm about halfway through. So far I haven't had any issues. But the new section has a lot of changes in Dev to other components - do you want to follow the instruction I just posted to push that up?

**Comment by RikiSjachrani-COM** [comment]
@JacquelineGoltz-COM thanks for QA'ing my Standard Choice changes, I'll move them to Test. Also, Sharon wants the Alt Fire Suppression fee changes ready this afternoon and set the expressions back to be just read only. Less moving parts for the customer...

Sharon also wants be to get involved in anyway I can to completed this today, so let me know how I can assist with this.

**Comment by ChrisHagen-COM** [comment]
@JacquelineGoltz-COM @RikiSjachrani-COM 

Pushed expression builder modifications up to TEST. 

It had stopped working correctly because a "FIRSUPP-OnLoad" expression had been added _in addition to_ the scripts I added. This script hid the "Alter 3 or less Alternate Fire Suppression Devices" onload, but is not needed because the FIRSUPP-Alter script runs onload as well and hides that field if the checkmark isn't in "Alter Alternate Fire Suppression Devices". 

Because this script ran on every onload if the "Alter 3 or less Alternate Fire Suppression Devices" was checked and any other change on the page happened it would hide the field again. This is because lots of other Accela computations on the page can cause the onload function to be triggered. 

Once that was removed it worked correctly, switching it back to just "read-only" did not help with that portion. However this onload functionality has been restored. The only negative of this is that if someone clears the "Alter Alternate Fire Suppression Devices" and switches to something else the checkmark is still checked. This will not cause any extra fees to trigger since it needs both of them to be checked, but it could cause confusion when someone is looking at it on AA later.

**Comment by JacquelineGoltz-COM** [comment]
@RikiSjachrani-COM @ChrisHagen-COM 
Ok I am emailing Bill and telling him to test the Fire Alt Suppression. That checkbox issue needs to be resolved though.  I did run a record and you are correct the fees are assessing as required.

**Comment by JacquelineGoltz-COM** [comment]
@RikiSjachrani-COM  Could you send me the link to the latest version of the spreadsheet?  Bill added two custom field changes that I want to track.

**Comment by RikiSjachrani-COM** [comment]
@JacquelineGoltz-COM thanks for updating it, it's located at \\Fps1\data1\Information Technology\Applications and Systems\Accela\FireInspections\Change Requests\SR-17-0000475 FD Increase Fees and it's named Accela.MGO.2018.Fee.Schedules v3 wScope Changes.xlsx

**Comment by JacquelineGoltz-COM** [comment]
@RikiSjachrani-COM Would you like to QA the new fee TNKREMCHG that Bill informed me of yesterday.

It replaces the 3 original fees for Tank Removal.
