### ISSUE TITLE
SR-18-0000089 EN Accela AMO for mobile inspections 

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#24]
EN Accela AMO for mobile inspections - Engineering would like to use Accela AMO to perform their Erosion Control Inspections. From the meeting I had with Daniel Olivares, Theresa Nelson, and Matt Allie what IT would need to do is

\\Fps1\Information Technology\Applications and Systems\Accela\Engineering\SR-18-0000089 EN Accela AMO for mobile inspections

 - [x] Set up Accela so that it automatically schedules an inspection when an EC permit is created
 - [x] Automatically create a new inspection three weeks after a previous inspection is completed
 - [x] Set up a list of EC inspections in the Ad Hoc Engineering Reports section, so we can create our own reports
 - [ ] Show them how to create custom lists in AMO by zones

**Comment by RikiSjachrani-COM** [comment]
@ChrisBilik-COM I added my notes as a one note at \\Fps1\data1\Information Technology\Applications and Systems\Accela\Engineering\SR-18-0000089 EN Accela AMO for mobile inspections 

please take a look and let me know when you want to meet and discuss

**Comment by ChrisBilik-COM** [comment]
10-4, reviewing now, ill set up a meeting....are you here Friday?

**Comment by RikiSjachrani-COM** [comment]
Yeah, until 2:00

**Comment by RikiSjachrani-COM** [comment]
@BrendenPautsch-COM, Engineering is planning on doing inspections on their Erosion Control Permits and they want to have similar reporting options that you did for ROW Permits. So this would be a Adhoc Data view (or MadisonAccela Table) that has the inspection data at their finger tips. 

How much effort would it be to duplicate what you did for ROW Permits but for Erosion Control Permits? There might be somethings that won't translate exactly, but that's what they are looking for. 

I have this assigned to Chris, but it might be easier if you get involved since you did this for ROW permits. Let me know

**Comment by ChrisHagen-COM** [comment]
Talked with @RikiSjachrani-COM, Moved this back to DEV after testing revealed some issues.

Will need to test as a user all the way through resulting an inspection. Inspections were not being assigned and were not able to be resulted by users.

in addition need to change underlying data in views so that number fields are numbers, date fields are dates, etc. 

Also need a new adhoc report that lists things by upcoming estimated completion dates.

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 
A few questions on Erosion Control inspections:

1) Is there going to be more than one unit?
2)When autoassigning, are we using districts?
3) Are we using any of the existing districts, or are we going to need to create a new district for them?
4) Who should be in the districts?

For the inspector resulting issue, it looks like Theresa was not an inspector so could not, but Daniel Oliviare would have been able to. Theresa Nelson was not even in DEV.

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM Below are the basic items that need to be addressed

 - [ ] 1) The inspections should be assigned to the person assigned to the record
 - [ ] 2) Theresa should be able to result inspections
 - [ ] 3) The adhoc view should conform to the correct data types for reporting purposes

Anything outside of the above needs to be checked before doing any work.

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

Thanks, I don't think we talked about who it was to be assigned to, just that it should be assigned.

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM 

Thank you. I was being bone headed and was thinking "when she manually scheduled inspections". There is an option for ISA/ISB but it appears we don't use that set of events. 

As you said it was easy.

**Comment by ChrisHagen-COM** [comment]
@RikiSjachrani-COM ,

Everything is ready for QA in DEV. It took a bit longer for adhoc because I missed something and had to wait again for it to update.

I have the new report "Erosion Control Upcoming Completion" ordered by estimated completion date, and hid the "in compliance" statuses. If there is more than one scheduled it will show it. I am not sure how I can put a range variable in (like between -7 days and + 28 days). Is that even possible?

**Comment by RikiSjachrani-COM** [comment]
@ChrisHagen-COM Let's close this request and deal with any others as support issues
