### ISSUE TITLE
SR-18-0000178 Fire Outdoor Assembly Permit (New Record type)

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#36]
Fire Outdoor Assembly Permit (New Record type)

To Do
 - [x] forward to Bill again

Daily Log

Specifications

ASI 

Outdoor Assembly
•	Check boxes to select one:  Annual/Recurring       One-Time Event            Revision [these selections will drive the fee]
•	Capacity: TEXT BOX  w/ Number only format

Use Kitchen Hood Suppression as an example to setup record type. (Workflow, Fees, etc.)

Standard comments may be updated.
[Outdoor Assembly Notes.docx](https://github.com/City-of-Madison/Development-Team-2/files/2146964/Outdoor.Assembly.Notes.docx)

**Comment by JacquelineGoltz-COM** [comment]
•	Check boxes to select one:  Annual/Recurring       One-Time Event            Revision [these selections will drive the fee]   
Per Bill Sullivan this can be a dropdown box.

**Comment by RikiSjachrani-COM** [comment]
@ANavaGomez-COM Let's get together and get started on this

**Comment by JacquelineGoltz-COM** [comment]
Emailed Bill about naming convention for Sequence generator.

**Comment by JacquelineGoltz-COM** [comment]
@ANavaGomez-COM I have more information from Bill Sullivan for our Monday meeting.
The permit will be on ACA
The fees are:
a.	Annual/Recurring event                $250
b.	One Time Event                             $50
c.	Revision                                          $50

He will be sending us email/letter information and Standard comments.

**Comment by ANavaGomez-COM** [comment]
Thank you Jacqueline! Looking forward to our meeting on Monday.

**Comment by JacquelineGoltz-COM** [comment]
My email to Bill Sullivan:
Bill,

As work has begun on the new permit type Outdoor Assembly, I do have more questions for you in order to proceed.

•	Should there be another custom field that will have the location of the Outdoor Assembly?  We are only adding the event type and capacity.
•	I am using the Kitchenhood Suppression permit to lay the groundwork for this permit.  I think the Kitchenhood may be more complex than this new type. 
o	Will this new permit need the conditions on the Custom List tab?
o	Do you need Parcel information added?
o	Shortnotes and project type fields are used on kitchenhood, I assume this is not needed on this permit type. Let me know.

•	Are fees to be paid online at the time of submission or later in the process similar to the other permits?
•	Is there any inspection information that needs to be added?

Get back to me at your convenience.  Thank you!

**Comment by JacquelineGoltz-COM** [comment]
I will email Bill Sullivan regarding reports that need to be added or edited for this new record type.

**Comment by JacquelineGoltz-COM** [comment]
Met with Bill today.  He will remind Jerry to get us the standard comments.  We are to use the Fire Protection Work Order report for this permit type as well. I said we would mock up the current report in Dev and send him a copy.   Inspections are to be the same as sprinkler and alarm permits.  I will schedule a meeting with @ANavaGomez-COM  soon.

**Comment by JacquelineGoltz-COM** [comment]
@ANavaGomez-COM  Please go to SSRS report manager and look at the report in Dev or Test.  Fire/FireProtectSystemWorkPermit.  We will be adding this new permit type to this report.   Jerry said he has the standard comments ready, he just needs to send them.

**Comment by JacquelineGoltz-COM** [comment]
We have moved the new permit type to test.  I am ready to have Bill and/or Ann test.  We still need answers about the actual report attaching to the record.  Riki and I will go over this today.

**Comment by RikiSjachrani-COM** [comment]
Riki 10/10/2018 - From the bi-weekly fire meeting
 - [ ] Should auto assign to area inspector - check out the GIS code stuff

Notified Bill that this is ready to test

**Comment by RikiSjachrani-COM** [comment]
@JacquelineGoltz-COM I'm going to move this to closed, nice job moving this along
